### ISSUE TITLE
connector.dll

### ISSUE THREAD

**Issue by MikePapinski** [wild-bear-stack/BJF-Feeder-CSharp#1]
Looks like to connector.dll is corrupted or I can not make it load. Could you please advise?

> *** Please input feeder and username correctly. ***
System.DllNotFoundException: Unable to load DLL 'connector.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Feeder_CSharp.Feeder.ConnectToFeeder(String strIP, Int32 nPort, String strUserName)
   at Feeder_CSharp.Feeder.FuncThreadScrap() in \\Mac\Home\Desktop\repos\BJF-Feeder-CSharp\BJF_Feeder_CSharp\Feeder_CSharp\Feeder.cs:line 69
System.DllNotFoundException: Unable to load DLL 'connector.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Feeder_CSharp.Feeder.ConnectToFeeder(String strIP, Int32 nPort, String strUserName)
   at Feeder_CSharp.Feeder.FuncThreadScrap() in \\Mac\Home\Desktop\repos\BJF-Feeder-CSharp\BJF_Feeder_CSharp\Feeder_CSharp\Feeder.cs:line 69
System.DllNotFoundException: Unable to load DLL 'connector.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Feeder_CSharp.Feeder.ConnectToFeeder(String strIP, Int32 nPort, String strUserName)
   at Feeder_CSharp.Feeder.FuncThreadScrap() in \\Mac\Home\Desktop\repos\BJF-Feeder-CSharp\BJF_Feeder_CSharp\Feeder_CSharp\Feeder.cs:line 69
System.DllNotFoundException: Unable to load DLL 'connector.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Feeder_CSharp.Feeder.ConnectToFeeder(String strIP, Int32 nPort, String strUserName)
   at Feeder_CSharp.Feeder.FuncThreadScrap() in \\Mac\Home\Desktop\repos\BJF-Feeder-CSharp\BJF_Feeder_CSharp\Feeder_CSharp\Feeder.cs:line 69
System.DllNotFoundException: Unable to load DLL 'connector.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Feeder_CSharp.Feeder.ConnectToFeeder(String strIP, Int32 nPort, String strUserName)
   at Feeder_CSharp.Feeder.FuncThreadScrap() in \\Mac\Home\Desktop\repos\BJF-Feeder-CSharp\BJF_Feeder_CSharp\Feeder_CSharp\Feeder.cs:line 69
System.DllNotFoundException: Unable to load DLL 'connector.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by MikePapinski** [comment]
my bad, now it is working, missing c++ libs
